### ISSUE TITLE
Something panics and no visible search results

### ISSUE THREAD

**Issue by davxy** [pop-os/cosmic-launcher#200] opened 2024-10-01 10:39 UTC
I tried last master branch (rev 5c9757b) and started `cosmic-launcher` from the terminal after killing the instance spawned by cosmic-session.

As I type into the search box, most of the times the results list is not updated and in the console where the program is started I get this panic:

![screenshot-2024-10-01-10-17-36](https://github.com/user-attachments/assets/958c6b26-693b-4ecf-85dd-62358416177d)

(I started the program with `RUST_BACKTRACE="full"` in order to understand where the panic happens)

Unfortunately I guess the panic happens in some other binary and not in the `cosmic-launcher` itself as:
1. no debug info is shown in the backtrace even if I build in debug mode (maybe the panic happens in some stripped binary that cosmic-launcher interacts with)
2. the cosmic-launcher program doesn't exit and I can continue getting panics if I type something else 

The other components of cosmic are part of Arch linux last alpha-2 packages: https://archlinux.org/packages/?sort=&q=cosmic&maintainer=&flagged=

For what is worth, I wasn't experiencing the same issue with alpha-1

**Comment by wash2** [comment] 2024-10-01 13:28
This is a duplicate of https://github.com/pop-os/cosmic-launcher/issues/191

**Closed by wash2** 2024-10-01 13:28 UTC

**Comment by davxy** [comment] 2024-10-01 14:29
https://github.com/pop-os/launcher/pull/241 solves my issue

**Comment by wash2** [comment] 2024-10-01 14:47
Great!
